-- Migration: Fix existing embeddings that are stored as strings
-- This script converts string embeddings back to proper vector format
-- Note: This only works if the strings are valid JSON arrays

-- First, let's check what format the embeddings are in
-- Run this query to see:
-- SELECT id, pg_typeof(embedding) as embedding_type, 
--        CASE WHEN embedding::text LIKE '[%' THEN 'JSON array' ELSE 'Other' END as format
-- FROM job_requests 
-- WHERE embedding IS NOT NULL
-- LIMIT 5;

-- If embeddings are stored as JSON strings, we need to convert them
-- However, if they're already corrupted, we may need to regenerate them

-- For now, the fix is in the application code to ensure embeddings are stored as arrays
-- Existing corrupted embeddings will need to be regenerated by:
-- 1. Re-saving the freelancer profile
-- 2. Re-creating the job request

-- To regenerate embeddings for existing records, you can:
-- 1. Update freelancer profiles: Have freelancers re-save their profiles
-- 2. Update job requests: Have clients re-create their jobs

-- Or manually fix in Supabase SQL Editor (if embeddings are JSON strings):
-- UPDATE job_requests 
-- SET embedding = embedding::text::vector(1536)
-- WHERE embedding IS NOT NULL 
--   AND embedding::text LIKE '[%';

-- UPDATE freelancer_profiles 
-- SET embedding = embedding::text::vector(1536)
-- WHERE embedding IS NOT NULL 
--   AND embedding::text LIKE '[%';


